<?php
namespace App\Livewire\Laboratory;
use App\Enums\LaboratoryOrderEstado;use App\Models\Laboratory\LaboratoryOrder;use App\Models\Laboratory\LaboratoryPackage;use App\Models\Laboratory\LaboratoryProfile;use App\Models\Laboratory\LaboratoryTest;use App\Models\Patient;use App\Services\Laboratory\LaboratoryOrderBuilderService;use Illuminate\Support\Facades\Auth;use Livewire\Component;use Livewire\WithPagination;
class LaboratoryOrderManager extends Component{use WithPagination; public ?int $patient_id=null; public array $test_ids=[]; public array $profile_ids=[]; public array $package_ids=[]; public ?string $observacion=null; public ?int $selectedOrderId=null;
public function save(LaboratoryOrderBuilderService $service){$this->validate(['patient_id'=>'required|exists:patients,id']);$service->createOrder(['patient_id'=>$this->patient_id,'user_id'=>Auth::id(),'fecha_orden'=>now()->toDateString(),'estado'=>LaboratoryOrderEstado::PENDIENTE->value,'observacion'=>$this->observacion],$this->test_ids,$this->profile_ids,$this->package_ids);$this->reset(['patient_id','test_ids','profile_ids','package_ids','observacion']);}
public function changeStatus($id,$status){LaboratoryOrder::findOrFail($id)->update(['estado'=>$status]);}
public function show($id){$this->selectedOrderId=$id;}
public function render(){return view('livewire.laboratory.order-manager',['patients'=>Patient::orderBy('nombres_apellidos')->get(['id','nombres_apellidos']),'tests'=>LaboratoryTest::where('estado',true)->orderBy('nombre')->get(['id','nombre']),'profiles'=>LaboratoryProfile::where('estado',true)->orderBy('nombre')->get(['id','nombre']),'packages'=>LaboratoryPackage::where('estado',true)->orderBy('nombre')->get(['id','nombre']),'orders'=>LaboratoryOrder::with(['patient:id,nombres_apellidos','user:id,name','items.test:id,nombre'])->latest()->paginate(10),'statuses'=>collect(LaboratoryOrderEstado::cases())->pluck('value')]);}
}
