<?php
namespace App\Livewire\Laboratory;
use App\Models\Laboratory\LaboratoryPackage;use App\Models\Laboratory\LaboratoryProfile;use App\Models\Laboratory\LaboratoryTest;use Livewire\Component;use Livewire\WithPagination;
class LaboratoryPackageCrud extends Component{use WithPagination; public string $search=''; public ?int $editingId=null; public string $nombre=''; public ?string $descripcion=null; public float $precio=0; public bool $estado=true; public array $test_ids=[]; public array $profile_ids=[];
protected function rules(){return ['nombre'=>'required|max:150|unique:laboratory_packages,nombre,'.($this->editingId??'NULL').',id'];}
public function edit($id){$p=LaboratoryPackage::with('items')->withTrashed()->findOrFail($id);$this->editingId=$id;$this->nombre=$p->nombre;$this->descripcion=$p->descripcion;$this->precio=(float)$p->precio;$this->estado=(bool)$p->estado;$this->test_ids=$p->items->where('tipo_item','test')->pluck('reference_id')->all();$this->profile_ids=$p->items->where('tipo_item','profile')->pluck('reference_id')->all();}
public function save(){ $this->validate(); $p=LaboratoryPackage::updateOrCreate(['id'=>$this->editingId],['nombre'=>$this->nombre,'descripcion'=>$this->descripcion,'precio'=>$this->precio,'estado'=>$this->estado]); $p->items()->delete(); foreach(array_unique($this->test_ids) as $id){$p->items()->create(['tipo_item'=>'test','reference_id'=>$id]);} foreach(array_unique($this->profile_ids) as $id){$p->items()->create(['tipo_item'=>'profile','reference_id'=>$id]);} $this->reset(['editingId','nombre','descripcion','test_ids','profile_ids']);$this->precio=0;$this->estado=true; }
public function delete($id){LaboratoryPackage::findOrFail($id)->delete();} public function restore($id){LaboratoryPackage::withTrashed()->findOrFail($id)->restore();}
public function render(){return view('livewire.laboratory.package-crud',['packages'=>LaboratoryPackage::withTrashed()->with('items')->when($this->search!=='',fn($q)=>$q->where('nombre','like',"%{$this->search}%"))->paginate(10),'tests'=>LaboratoryTest::where('estado',true)->get(['id','nombre']),'profiles'=>LaboratoryProfile::where('estado',true)->get(['id','nombre'])]);}}
